#!/usr/bin/env bash
# Usage: main echo <args>...
# Summary: Echoes its arguments
# Help: This is a complete test script with documentation.
#
# The help section can span multiple lines.

set -e

echo "$@"
